name: Update Docker Image Tags

on:
  schedule:
    # Runs once a day at midnight
    - cron: '0 0 * * *'
  # Manual trigger option
  workflow_dispatch:

jobs:
  update-image-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Determine branch and tag prefix
        id: branch-check
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          echo "branch=$BRANCH_NAME" >> $GITHUB_OUTPUT
          
          if [[ "$BRANCH_NAME" == "main" ]]; then
            echo "tag_prefix=stable-" >> $GITHUB_OUTPUT
          else
            echo "tag_prefix=unstable-" >> $GITHUB_OUTPUT
          fi

      - name: Check for new Docker image tags
        id: check-tags
        run: |
          # Docker repository for BrokenCrystals
          DOCKER_REPO="brightsec/brokencrystals"
          TAG_PREFIX="${{ steps.branch-check.outputs.tag_prefix }}"
          
          echo "Checking for new tags with prefix: $TAG_PREFIX"
          
          # Get latest tag with the appropriate prefix
          LATEST_TAG=$(curl -s "https://hub.docker.com/v2/repositories/${DOCKER_REPO}/tags?page_size=100" | \
            jq -r '.results[].name' | \
            grep "^${TAG_PREFIX}" | \
            sort -V | \
            tail -n1)
          
          echo "Latest tag found: $LATEST_TAG"
          echo "latest_tag=$LATEST_TAG" >> $GITHUB_OUTPUT
          
          # Check current tag in values.yaml
          CURRENT_TAG=$(grep -A1 "images:" charts/brokencrystals/values.yaml | grep "main:" | awk '{print $2}')
          echo "Current tag: $CURRENT_TAG"
          
          if [ "$CURRENT_TAG" != "$LATEST_TAG" ]; then
            echo "update_needed=true" >> $GITHUB_OUTPUT
          else
            echo "update_needed=false" >> $GITHUB_OUTPUT
          fi

      - name: Update values.yaml
        if: steps.check-tags.outputs.update_needed == 'true'
        run: |
          LATEST_TAG="${{ steps.check-tags.outputs.latest_tag }}"
          BRANCH_NAME="${{ steps.branch-check.outputs.branch }}"
          
          # Update the values.yaml file
          sed -i "s/main: .*$/main: $LATEST_TAG/" charts/brokencrystals/values.yaml
          
          # Create a branch for the PR
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
          PR_BRANCH_NAME="update-docker-image-tag-${LATEST_TAG}"
          git checkout -b $PR_BRANCH_NAME
          
          git add charts/brokencrystals/values.yaml
          git commit -m "Update brokencrystals Docker image tag to $LATEST_TAG"
          git push origin $PR_BRANCH_NAME

      - name: Create Pull Request
        if: steps.check-tags.outputs.update_needed == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Update brokencrystals Docker image tag to ${{ steps.check-tags.outputs.latest_tag }}"
          body: |
            This PR updates the brokencrystals Docker image tag from the current tag to `${{ steps.check-tags.outputs.latest_tag }}`.
            
            This update was automatically generated by GitHub Actions.
          branch: update-docker-image-tag-${{ steps.check-tags.outputs.latest_tag }}
          base: ${{ steps.branch-check.outputs.branch }}
          delete-branch: true
